import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import NextAuthProvider from "./util/NextAuthProvider";
import Header from "./components/Header/Header";
import { trackEvent } from "./util/MixPanel";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await trackEvent("page_view");

  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
        <NextAuthProvider>
          <Theme
            appearance="dark"
            accentColor="tomato"
            grayColor="mauve"
            radius="none"
          >
            <Header />
            {children}
          </Theme>
        </NextAuthProvider>
      </body>
    </html>
  );
}
