import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import NextAuthProvider from "./context/NextAuthProvider"
import Header from "./components/Header"

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
        <Theme
          appearance="dark"
          accentColor="tomato"
          grayColor="mauve"
          radius="none"
        >
          <Header />
          {children}
        </Theme>
        </NextAuthProvider>
      </body>
    </html>
  );
}
