// Code generated by Slice Machine. DO NOT EDIT.
import dynamic from 'next/dynamic'

export const components = {
  blog_content: dynamic(() => import('./BlogContent')),
  call_to_action: dynamic(() => import('./CallToAction')),
}
